import Head from "next/head";
import Link from "next/link";

import { api } from "@/utils/api";

export default function Home() {
  return (
    <>
      <Head>
        <title>How was your day?</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen items-center justify-center">
        Hello World
      </main>
    </>
  );
}
